# Hi there!
# These are the settings for Selfstarter.
# This is more tidy than changing the HTML if all you want to do is rename things and swap out images

# You should totally change the HTML and CSS though
# Checkout app/assets/stylesheets/variables.css.scss to change around the CSS quickly

# Set your project goal here - if you manually want to adjust your progress to test the site, head over to the Order model (app/models/order.rb)
project_goal: 100
# If you want to edit the FAQ, head over to app/views/preorder/homepage/_faqs.html.erb

# This'll be both the page title (<title></title>) and the name in the header
product_name: "Selfstarter"

# An image showcasing your product -- it'll show up when you pin your product
# It should be in app/assets/images
product_image_path: "my-product-image.png"

# The message on the preorder page, Lockitron's 
value_proposition: "Roll your own crowdfunding"

# YouTube or Vimeo Video URL (The embed URL, without the query string options)
video_embed_url: "https://www.youtube.com/v/D1L3o88GKew"

# If set to true, then the image at "/assets/video_placeholder.png" will be shown in place of the youtube
# video.  When the user clicks it, the vid will replace the image and start playing.
#
# NOTE: you can set this to false, and no image will be use - first frame of the video will be displayed
#
# NOTE: this only works for youtube video at the moment.  If its not for youtube, then just leave this property blank
use_video_placeholder: true

# Amazon settings -- you'll need an Amazon Payments account, sign up here --> http://bit.ly/SGksTv

# To find your access key and secret key, head over to here --> http://bit.ly/R4I4ky (Follow that guide in the Seller Central page)
amazon_access_key: "YOUR_AMAZON_ACCESS_KEY"
amazon_secret_key: "YOUR_AMAZON_SECRET_KEY"
price: 	19.95

# To allow different packages ("rewards" for funding) with different pricing on the payments page, set this to true
use_payment_options: true

# if use_payment_options is set to true, then a set of radio buttons will be displayed with various payment options
# payment_options is a comma delimited list of:
#   amount (the cost of the package in dd.cc),
#   display ammount (the text to display on the web page for the cost)
#   shipping description,
#   package text (description of what they get if they select this payment option - kickstarter calls these "rewards"),
#   delivery text
payment_options: [
  ["10.00", "$10", "", "<strong>Basic level: </strong>You receive a great big thankyou from us!  You Rock", ""],
  ["100.00", "$100", "add $3 to ship outside the US", "<strong>Package 1: </strong>You receive our print edition", "Estimated delivery: Oct 2013"],
  ["125.00", "$125", "add $3 to ship outside the US", "<strong>Package 2: </strong>You will receive both our print and digital edition", "Estimated delivery: Oct 2013"],
  ["125.00", "$125", "add $3 to ship outside the US", "You will receive both our print and digital edition", "Estimated delivery: Oct 2013"],
  ["125.00", "$125", "add $3 to ship outside the US", "You will receive both our print and digital edition", "Estimated delivery: Oct 2013"],
  ["125.00", "$125", "add $3 to ship outside the US", "You will receive both our print and digital edition", "Estimated delivery: Oct 2013"],
  ["125.00", "$125", "add $3 to ship outside the US", "You will receive both our print and digital edition", "Estimated delivery: Oct 2013"],
  ["125.00", "$125", "add $3 to ship outside the US", "You will receive both our print and digital edition", "Estimated delivery: Oct 2013"]
]

payment_description: "You really should change this text because people will see it on Amazon's order page!!!!!"

# Amazon limits how much we can charge people with their Multi-Use tokens.
# You probably should add some leeway to account for international shipping
charge_limit: 25.00

# Stats settings

# On Lockitron, it's "backers"
primary_stat: "backers"
# This'll show up in the tweet as, "I'm forker number ..."
primary_stat_verb: 'backer'

# The 2nd call to action button, towards the middle-ish of the page
middle_reserve_text: "Reserve Now"

# When the project should end
expiration_date: <%= DateTime.now + 29 %>

# Text to show inside the progress bar, when the goal reaches/exceeds 100%
progress_text: "Implemented"

# Call to action section

# On Lockitron, it's "First Batch Ships in March 2013"
ships: "Ships...sometime"

# On Lockitron, it's "Reserve Now"
call_to_action: "Reserve Now"
# On Lockitron, this is "Only $149 for a limited time"
price_human: "It costs money!"

# The paragraph below the price. You'd probably say something about how you're not going to charge them before it ships (so it's less risky).
dont_give_them_a_reason_to_say_no: "You'll get this exact site. All you'll need to get started is a great product."

# Social Stuff
facebook_app_id: "1234567890"
# Tweets are prefixed with "I'm #{Settings.primary_stat} number X for #{Settings.product_name}"
# Maybe mention something about your product vision -- e.g. "to replace keys with my phone"
tweet_text: "to crowdfund"

# Google Analytics
google_id: "1234567890"

# If you want to change the images for the key points (e.g. "Kickstarter is not a store")
# They're in app/assets/images/#{pointer_number}-background.png
# So, the first key point, it's at app/assets/images/1-background.png
# Alternatively, change it up in app/assets/stylesheets/homepage/key_points.css.scss